[project]
name = "zfin-orthology-ingest"
version = "0.0.0"
description = "Transform of ZFIN's curated orthology file into Biolink compliant KGX"
readme = "README.md"
license = "BSD-3-Clause"
requires-python = ">=3.10"
authors = [
    { name = "Kevin Schaper", email = "kevin@tislab.org" }
]
dependencies = [
    "koza>=2.0.0",
    "kghub-downloader>=0.4.1",
    "biolink-model>=4.2.0",
    "duckdb>=0.10.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.uv]
dev-dependencies = [
    "pytest>=8.1.1",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D211",
    "D212",
    "D203",
    "F541",
    "S101",
]
fixable = ["ALL"]
select = [
    "B",
    "D",
    "E",
    "F",
    "I",
    "S",
    "W",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "S"]
